version: '3.9'

services:
  server:
    build: .
    restart: always
    ports:
      - 4000:4000
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=admin
