version: '3.9'

services:
  server:
    build: .
    restart: always
    ports:
      - 6000:6000
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgres:/var/lib/postgresql
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis:/data

      
volumes:
  postgres:
  redis:
